{% block running_step_name %}
Verify Workbench Instance Jupyter is running on port 127.0.0.1:8080
{% endblock running_step_name %}

{% block running_success_reason %}
OK! Workbench Instance {instance_name} syslogs indicate Jupyter is running on port 127.0.0.1:8080
{% endblock running_success_reason %}

{% block running_failure_reason %}
Workbench Instance {instance_name} syslogs indicate Jupyter is NOT running on port 127.0.0.1:8080
{% endblock running_failure_reason %}

{% block running_failure_reason_a1 %}
Workbench Instance {instance_name} syslogs indicate Jupyter is running on a port different to 127.0.0.1:8080
{% endblock running_failure_reason_a1 %}

{% block running_failure_remediation %}
If the instance is stopped, start it and rerun this check.
You may also need to extend the logging query start and end times.
Only port 8080 is supported. Installed extensions, packages or custom scripts may cause the port to change.

1. Try following documentation [1] [2] [3]
2. If it doesn't work, recover data by diagnosing the instance with the --enable-copy-home-files [4]
3. Create a new Instance and migrate your data [5]

[1] https://cloud.google.com/vertex-ai/docs/general/troubleshooting-workbench?component=any#verify-jupyter-service
[2] https://cloud.google.com/vertex-ai/docs/general/troubleshooting-workbench?component=any#verify-jupyter-internal-api
[3] https://cloud.google.com/vertex-ai/docs/general/troubleshooting-workbench?component=any#restart-jupyter-service
[4] https://cloud.google.com/sdk/gcloud/reference/workbench/instances/diagnose
[5] https://cloud.google.com/vertex-ai/docs/workbench/instances/migrate
{% endblock running_failure_remediation %}
