location=europe-west10,name=gcp-cluster,project_id=gcpdiag-gke-cluster-autoscaler-rrrr

gke/cluster-autoscaler: Analyses logs in the project where the cluster is running.

  If there are log entries that contain messages listed in the public documentation
  https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-autoscaler-visibility#messages
  then provide details on how each particular issue can be solved.

  The following ScaleUP logs messages are covered:
  - scale.up.error.out.of.resources
  - scale.up.error.quota.exceeded
  - scale.up.error.waiting.for.instances.timeout
  - scale.up.error.ip.space.exhausted
  - scale.up.error.service.account.deleted

  The following ScaleDown logs messages are covered:
  - scale.down.error.failed.to.evict.pods
  - no.scale.down.node.node.group.min.size.reached
  - no.scale.down.node.scale.down.disabled.annotation
  - no.scale.down.node.minimal.resource.limits.exceeded
  - no.scale.down.node.no.place.to.move.pods
  - no.scale.down.node.pod.not.backed.by.controller
  - no.scale.down.node.pod.not.safe.to.evict.annotation
  - no.scale.down.node.pod.kube.system.unmovable
  - no.scale.down.node.pod.not.enough.pdb
  - no.scale.down.node.pod.controller.not.found
  - no.scale.down.node.pod.unexpected.error

  
[START]: Check the provided parameters.
[AUTOMATED STEP]: Check for "scale.up.error.out.of.resources" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleUp event failed because some of the MIGs could not be increased due to lack of resources.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     Follow the documentation:
     https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-vm-creation#resource_availability

[AUTOMATED STEP]: Check for "scale.up.error.quota.exceeded" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleUp event failed because some of the MIGs could not be increased, due to exceeded Compute Engine quota.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     Check the Errors tab of the MIG in Google Cloud console to see what quota is being exceeded. Follow the instructions to
     request a quota increase:
     https://cloud.google.com/compute/quotas#requesting_additional_quota

[AUTOMATED STEP]: Check for "scale.up.error.waiting.for.instances.timeout" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleUp event failed because instances in some of the MIGs failed to appear in time.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     This message is transient. If it persists, engage Google Cloud Support for further investigation.

[AUTOMATED STEP]: Check for "scale.up.error.ip.space.exhausted" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleUp event failed because the cluster doesn't have enough unallocated IP address space to use to add new nodes or
     Pods.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     Refer to the troubleshooting steps to address the lack of IP address space for the nodes or pods.
     https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips#not_enough_space

[AUTOMATED STEP]: Check for "scale.up.error.service.account.deleted" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleUp event failed because a service account used by Cluster Autoscaler has been deleted.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     Engage Google Cloud Support for further investigation.

[AUTOMATED STEP]: Check for "no.scale.down.node.node.group.min.size.reached" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     Node cannot be removed because its node group is already at its minimum size.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     Review and adjust the minimum value set for node pool autoscaling.
     https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-autoscaler#resizing_a_node_pool

[AUTOMATED STEP]: Check for "scale.down.error.failed.to.evict.pods" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleDown event failed because some of the Pods could not be evicted from a node.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     Review best practices for Pod Disruption Budgets to ensure that the rules allow for eviction of application replicas
     when acceptable.
     https://cloud.google.com/architecture/best-practices-for-running-cost-effective-kubernetes-applications-on-gke#add-pod_disruption_budget-to-your-application

[AUTOMATED STEP]: Check for "no.scale.down.node.scale.down.disabled.annotation" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleDown event failed because the node is annotated with cluster-autoscaler.kubernetes.io/scale-down-disabled:
     true.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     Cluster autoscaler skips nodes with this annotation without considering their utilization and this message is logged
     regardless of the node's utilization factor.
     If you want cluster autoscaler to scale down these nodes, remove the annotation.

[AUTOMATED STEP]: Check for "no.scale.down.node.minimal.resource.limits.exceeded" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleDown event failed because it would violate cluster-wide minimal resource limits.
     These are the resource limits set for node auto-provisioning.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     Review your limits for memory and vCPU and, if you want cluster autoscaler to scale down this node, decrease the limits
     by following the documentation
     https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning#enable

[AUTOMATED STEP]: Check for "no.scale.down.node.no.place.to.move.pods" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleDown event failed because there's no place to move Pods.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     If you expect that the Pod should be rescheduled, review the scheduling requirements of the Pods on the underutilized
     node to determine if they can be moved to another node in the cluster.
     To learn more, see the link
     https://cloud.google.com/kubernetes-engine/docs/troubleshooting/cluster-autoscaler-scale-down#no-place-to-move-pods

[AUTOMATED STEP]: Check for "no.scale.down.node.pod.not.backed.by.controller" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleDown event failed because a Pod is not backed by a controller such as ReplicationController, DaemonSet, Job,
     StatefulSet, or ReplicaSet.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     Set the annotation "cluster-autoscaler.kubernetes.io/safe-to-evict": "true" for the Pod or define an acceptable
     controller

[AUTOMATED STEP]: Check for "no.scale.down.node.pod.not.safe.to.evict.annotation" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleDown event failed because a Pod on the node has the safe-to-evict=false annotation
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     If the Pod can be safely evicted, edit the manifest of the Pod and update the annotation to
     "cluster-autoscaler.kubernetes.io/safe-to-evict": "true".

[AUTOMATED STEP]: Check for "no.scale.down.node.pod.kube.system.unmovable" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleDown event failed because the pod is a non-DaemonSet, non-mirrored, Pod without a PodDisruptionBudget in the
     kube-system namespace.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     By default, Pods in the kube-system namespace aren't removed by cluster autoscaler.

     To resolve this issue, either add a PodDisruptionBudget for the kube-system Pods or use a combination of node pools
     taints and tolerations to separate kube-system Pods from your application Pods.
     To learn more, see
     https://cloud.google.com/kubernetes-engine/docs/troubleshooting/cluster-autoscaler-scale-down#kube-system-unmoveable

[AUTOMATED STEP]: Check for "no.scale.down.node.pod.not.enough.pdb" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The scaleDown event failed the pod doesn't have enough PodDisruptionBudget.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     Review the PodDisruptionBudget for the Pod and consider making it less restrictive.
     To learn more, see
     https://cloud.google.com/kubernetes-engine/docs/troubleshooting/cluster-autoscaler-scale-down#not-enough-pdb

[AUTOMATED STEP]: Check for "no.scale.down.node.pod.controller.not.found" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     Pod is blocking the ScaleDown event because its controller (for example, a Deployment or ReplicaSet) can't be found.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     To determine what actions were taken that left the Pod running after its controller was removed, review the logs. To
     resolve this issue, manually delete the Pod.

[AUTOMATED STEP]: Check for "no.scale.down.node.pod.unexpected.error" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     Pod is blocking the ScaleDown event because of an unexpected error.
     Example log entry that would help identify involved objects:
     {'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'service-12340002@container-engine-robot.iam.gserviceaccount.com'}, 'requestMetadata': {'callerIp': '2002:a17:907:3ea4::', 'callerSuppliedUserAgent': 'google-api-go-client/0.5 GoogleContainerEngine/v1'}, 'serviceName': 'compute.googleapis.com', 'methodName': 'beta.compute.instanceGroupManagers.insert', 'resourceName': 'projects/gcpdiag-gke1-aaaa/zones/europe-west4-a/instanceGroupManagers/gke-gke1-default-pool-dc4a8b29-grp', 'request': {'@type': 'type.googleapis.com/compute.instanceGroupManagers.insert'}}, 'insertId': '-tt9mudi768', 'resource': {'type': 'gce_instance_group_manager', 'labels': {'location': 'europe-west4-a', 'instance_group_manager_id': '318228385164940970', 'project_id': 'gcpdiag-gke1-aaaa', 'instance_group_manager_name': 'gke-gke1-default-pool-dc4a8b29-grp'}}, 'timestamp': '2021-11-24T16:29:21.943390Z', 'severity': 'NOTICE', 'logName': 'projects/gcpdiag-gke1-aaaa/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1637771331527-5d18b5a706163-f238dbec-106555c8', 'producer': 'compute.googleapis.com', 'last': True}, 'receiveTimestamp': '2021-11-24T16:29:22.710110506Z'}

     [REMEDIATION]
     The root cause of this error is unknown. Contact Cloud Customer Care for further investigation.

[END]: Finalize `Cluster Autoscaler` diagnostics.


